# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

DB_HOSTNAME: "aa13dhd3ngpk50h.cd0xxu3beoik.us-west-2.rds.amazonaws.com" 
DB_USER: "root"
DB_PASSWORD: "kme2004cy"
SECRET_KEY_BASE: "cc37a9206e52b82f57bd0b728d7c90f5208ff0f0269c4d88daf2de4bdca42f63ed0b44acaaf2aa9cd29fbe4c394230e1c9caf86c9238b06c5d1a97503fece60e"
